finished mark implementation

diff --git a/tasksh b/tasksh
--- a/tasksh
+++ b/tasksh
@@ -556,7 +556,7 @@ mark() {
                     exit 1
                 fi
 
-                TASK_STATUS="ACTIVE"
+                TASK_STATUS="DONE"
 
                 shift 2
                 ;;
@@ -581,9 +581,39 @@ mark() {
         esac 
     done
 
-    echo $TASK_ID
+    # the id.*.*.* is because in the task file format, there are 3 dots seperating id, scheduling, type, and status
+    if ! TASK_PATH=$(ls "$TASKSH_DIR/$TASK_ID".*.*.* -R 2>/dev/null); then
+        echo "No task with ID $TASK_ID found"
+        exit 1
+    fi
 
-    # TODO IMPLEMENT TASK PARSING
+    if [ "$(echo "$TASK_PATH" | wc -l)" -gt 1 ]; then
+        echo "Multiple matches found, this is likely do manually modification of tasksh folder ($TASKSH_DIR). This requires a manually fix, inside the tasksh folder, change the file names such that no tasks share the same id (file name format is ID.SCHEDULING.TYPE.STATUS."
+        echo "$TASK_PATH"
+        exit 1
+    fi
+
+
+    if [ "$TASK_STATUS" = "ACTIVE" ]; then
+        TASK_PATH_NEW=$(echo "$TASK_PATH" | sed 's/.DONE$/.ACTIVE/')
+    elif [ "$TASK_STATUS" = "DONE" ]; then
+        TASK_PATH_NEW=$(echo "$TASK_PATH" | sed 's/.ACTIVE$/.DONE/')
+    else
+        echo "INVALID TASK_STATUS! THIS IS A PROBLEM WITH TASKSH"
+        exit 1
+    fi
+
+
+    if [ "$TASK_PATH" = "$TASK_PATH_NEW" ]; then
+        echo "task $TASK_ID is already $TASK_STATUS"
+        exit 0
+    fi
+
+    if ! mv "$TASK_PATH" "$TASK_PATH_NEW"; then
+        echo "Failed to update task due to failure to rename task file ($TASK_PATH)"
+        echo "This is likely a permissions error. Ensure that the folder and file has read and write permissions"
+        exit 1
+    fi
 }
 
 edit() {
