added handling for no args mark mode edgecase

diff --git a/tasksh b/tasksh
--- a/tasksh
+++ b/tasksh
@@ -507,6 +507,11 @@ config() {
 mark() {
     shift # shift over mode
 
+    if [ "$#" -eq 0 ]; then
+        echo "task id is required for mark mode."
+        exit 1
+    fi
+
     # when marking, default to done
     TASK_STATUS="DONE"
 
@@ -564,7 +569,7 @@ mark() {
                 if ( echo "${1:--x}" | grep -qe '^-.*' ); then
                     echo "$1 is an invalid options, see help (-h, --help) for available options"
                     exit 1
-                elif ( echo "$2" | grep -qe "^[0-9][0-9]*$" ); then
+                elif ( echo "$1" | grep -qe "^[0-9][0-9]*$" ); then
                     TASK_ID=$1
                 else
                     echo "invalid task id, task ids can only be unsigned integer numbers"
@@ -575,6 +580,8 @@ mark() {
                 ;;
         esac 
     done
+
+    echo $TASK_ID
 
     # TODO IMPLEMENT TASK PARSING
 }
